spring.application.name=gpsroot

spring.main.lazy-initialization=true
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/gpsrootdb}
spring.datasource.username=${DATABASE_USERNAME:gpsroot}
spring.datasource.password=${DATABASE_PASSWORD:gpsroot}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}

security.jwt.secret = "orxanorxanorxanorxanorxanorxanorxanorxanorxanorxanorxanorxanorxa"

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=orkhansmail@gmail.com
spring.mail.password=pkfknandivmkasxs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.secret-key=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET
app.qr-ttl-seconds=30
app.office-lat=40.4271462
app.office-lng=49.8850268
app.allowed-radius-meters=150

spring.data.redis.host=localhost
spring.data.redis.port=6379

google.client.id=812918307154-plcha25a1jbdm57gudq6egmhi4j4fpdn.apps.googleusercontent.com

management.endpoints.web.exposure.include=health,prometheus,metrics
management.metrics.tags.application=gpsroot

logging.level.org.springframework.security=DEBUG
